config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :visitors
  resources :parks
  resources :rides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    belongs_to :park, optional: true
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]
  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
    @park = Park.all.map{|p| [p.pname, p.pno]}
    @park_options = Park.all.map{|p| [p.pname, p.pno]}

  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @visitors = Visitor.all
    @park = Park.all.map{|p| [p.pname, p.pno]}
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
  end

  # GET /visitors/new
  def new
    @park = Park.find_by(params[:pno])
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @park = Park.find_by(params[:visitor["visits"]])
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
    @visitor = Visitor.new(visitor_params)
    redirect_to thank_path
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:vname, :vemail, :contact, :visitDate, :noOfTickets, :visits)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :vname %>
  </div>

  <div class="field">
    <%= form.label :"E-mail" %>
    <%= form.text_field :vemail%>
  </div>

  <div class="field">
    <%= form.label :Contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :"Date of visit" %>
    <%= form.date_field :visitDate , value:Date.today, readonly:true %>
  </div>

  <div class="field">
    <%= form.label :"Number of tickets" %>
    <%= form.number_field :noOfTickets, min: 1%>
  </div>

  <div class="field">
    <%= form.label :"Park you would like to visit" %>
    <%= select(:visitor, :visits, @park_options) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <style type="text/css">
      body{
        background: url("/assets/151205.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        height: 100%
        overflow: hidden;
        font-family: 'Bangers', cursive;
        font-size-adjust: auto;
        font-size: 20px;
      }
      * {box-sizing: border-box}

      /* Overwrite default styles of hr */
      hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
      }
      .content {
        background: white;
        width: 50%;
        padding: 40px;
        margin: 100px auto;
      }

      h1{
        text-shadow: 1px 1px black;
        font-size: 60px;
        color: #272748;
        text-align: center;

      }
      h3{
        font-size: 22px;
        color: #272748;
        text-align: left;
      }


      p{
        font-size: 16px;
        text-align: left;
        /*line-height: 2;*/
        letter-spacing: 1px;
        color: black;
        font-family: Verdana, Geneva, sans-serif;


      }
      .button {
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #272748;
        align: center;
        cursor: pointer;
        border-radius: 5px;
      }

    </style>
    <meta charset="utf-8">
  </head>
  <body>

    <div class="content">
      <h1>Visitors</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>E-mail</th>
            <th>Contact</th>
            <th>Date of Visit</th>
            <th>Number of tickets</th>
            <th>Park visited</th>
            <th colspan="6"></th>
          </tr>
        </thead>

        <tbody>
          <% @visitors.each do |visitor| %>
            <tr>
              <td><%= visitor.vname %></td>
              <td><%= visitor.vemail %></td>
              <td><%= visitor.contact %></td>
              <td><%= visitor.visitDate %></td>
              <td><%= visitor.noOfTickets %></td>
              <td><%= @park["#{visitor.visits}".to_i-1][0] %></td>
              <td><%= link_to 'Show', visitor %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Visitor', new_visitor_path %>
    </div>
  </body>
</html>

<p id="notice"><%= notice %></p>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <style type="text/css">
      body{
        background: url("/assets/151205.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        height: 100%
        overflow: hidden;
        font-family: 'Bangers', cursive;
        font-size-adjust: auto;
        font-size: 20px;
      }
      * {box-sizing: border-box}

      /* Overwrite default styles of hr */
      hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
      }
      .content {
        background: white;
        width: 50%;
        padding: 40px;
        margin: 100px auto;
      }

      h2{
        text-shadow: 1px 1px black;
        font-size: 60px;
        color: #272748;
        text-align: center;

      }
      h3{
        font-size: 22px;
        color: #272748;
        text-align: left;
      }


      p{
        font-size: 16px;
        text-align: left;
        /*line-height: 2;*/
        letter-spacing: 1px;
        color: black;
        font-family: Verdana, Geneva, sans-serif;


      }
      .button {
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #272748;
        align: center;
        cursor: pointer;
        border-radius: 5px;
      }

    </style>
    <meta charset="utf-8">
  </head>
  <body>

    <div class="content">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @visitor.vname %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @visitor.vemail %>
      </p>

      <p>
        <strong>Contact:</strong>
        <%= @visitor.contact %>
      </p>

      <p>
        <strong>Date of Visit:</strong>
        <%= @visitor.visitDate %>
      </p>

      <p>
        <strong>Number of tickets:</strong>
        <%= @visitor.noOfTickets %>
      </p>

      <p>
        <strong>Park visited:</strong>
        <%= @park["#{@visitor.visits}".to_i-1][0] %>
      </p>



      <%= link_to 'Edit', edit_visitor_path(@visitor) %> |
      <%= link_to 'Back', visitors_path %>
    </div>
  </body>
</html>