config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :visitors
  resources :parks
  resources :rides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ride.rb
class Ride < ApplicationRecord
    belongs_to :park, optional: true
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_ride, only: [:show, :edit, :update]

  # GET /rides
  # GET /rides.json
  def index
    @park = Park.all.map{|p| [p.pname, p.pno]}
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
    @park = Park.all.map{|p| [p.pname, p.pno]}
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
  end

  # GET /rides/new
  def new
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
  end

  # POST /rides
  # POST /rides.json
  def create
    @park_options = Park.all.map{|p| [p.pname, p.pno]}
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ride_params
      params.require(:ride).permit(:rno, :rname, :exists_in)
    end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Ride number" %>
    <%= form.number_field :rno, min: 1%>
  </div>

  <div class="field">
    <%= form.label :"Ride name" %>
    <%= form.text_field :rname %>
  </div>

  <div class="field">
    <%= form.label :"Park that the ride belongs to" %>
    <%= select(:ride, :exists_in, @park_options) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h2>Editing Ride</h2>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Rides</h2>

<table>
  <thead>
    <tr>
      <th>Ride number</th>
      <th>Ride name</th>
      <th>Park name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.rno %></td>
        <td><%= ride.rname %></td>
        <td><%= @park["#{ride.exists_in}".to_i-1][0] %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h2>New Ride</h2>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ride number:</strong>
  <%= @ride.rno %>
</p>

<p>
  <strong>Ride name:</strong>
  <%= @ride.rname %>
</p>

<p>
  <strong>Park name:</strong>
  <%= @park["#{@ride.exists_in}".to_i-1][0] %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>