config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :visitors
  resources :parks
  resources :rides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>  
<title>Amusement Park</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <h1>Welcome to the Amusement Park</h1>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  employee_session , class: "btn "%></li>
        <% if employee_signed_in? %>
          <li><%= link_to "Account", edit_employee_registration_path, class: "btn "  %></li>
          <li><%= link_to "Parks", parks_path, class: "btn" %></li>
          <li><%= link_to "Rides", rides_path, class: "btn" %></li>
          <li><%= link_to "Visitors", visitors_path, class: "btn" %></li>
          <li>
            <%= link_to('Logout', destroy_employee_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_employee_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_employee_session_path, class: "btn " %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>